/*
 * SubtitleCorrector - content script (isolated world).
 *
 * Orkestratie:
 *   - luistert naar events van de page agent (video-wissel, ads, ondertitels)
 *   - past automatisch toe bij elke nieuwe YouTube-video (indien aan)
 *   - handmatige trigger met de hotkey (standaard "]")
 *   - vraagt de lokale bridge om audio-analyse als metadata niet genoeg is
 *   - toont een korte toast in de player
 */
(function () {
  'use strict';

  var L = globalThis.SCLang;
  if (!L) return;

  var DEFAULT_SETTINGS = {
    enabled: true,
    hotkey: ']',
    hotkeyEnabled: true,
    hotkeyToggleSubtitles: false,
    autoApply: true,
    preferAutoGenerated: true,
    forceSubtitlesOn: true,
    respectUserOff: true,
    fixTranslation: true,
    audioFallback: true,
    captionPriority: true,
    audioFallbackInPlaylists: false,
    captionBoost: true,
    captionSize: 175,
    captionLines: 2,
    captionOffset: 7,
    captionWidth: 70,
    captionFont: 'youtube',
    captionWeight: 500,
    captionWordByWord: true,
    audioSeconds: 5,
    minConfidence: 0.5,
    keepAudioDuringCapture: true,
    showToast: true,
    toastMs: 3800,
    debug: false
  };

  var settings = {};
  var state = {
    videoId: null,
    busy: false,
    fixed: Object.create(null),     // videoId -> {sig, at, lang}
    optedOut: Object.create(null),  // videoId -> true (gebruiker zette subs zelf uit)
    lastProbe: null,
    lastResult: null,
    autoTimer: null,
    retry: null,
    waitingPlayback: null,
    retryCount: 0,
    lastCaptureAt: 0,
    subtitlesOff: false,
    fixCooldown: Object.create(null)
  };

  // Laag 4 (audio-analyse) is zwaar; nooit vaker dan één keer per 45 s automatisch.
  var CAPTURE_COOLDOWN_MS = 45000;

  /* ------------------------------------------------------------------ *
   * Instellingen
   * ------------------------------------------------------------------ */
  function loadSettings(cb) {
    try {
      chrome.storage.sync.get(DEFAULT_SETTINGS, function (items) {
        settings = Object.assign({}, DEFAULT_SETTINGS, items || {});
        cb();
      });
    } catch (e) {
      settings = Object.assign({}, DEFAULT_SETTINGS);
      cb();
    }
  }

  try {
    chrome.storage.onChanged.addListener(function (changes, area) {
      if (area !== 'sync') return;
      var touched = false;
      Object.keys(changes).forEach(function (k) {
        if (Object.prototype.hasOwnProperty.call(DEFAULT_SETTINGS, k)) {
          settings[k] = changes[k].newValue;
          touched = true;
        }
      });
      if (touched) {
        if (settings.debug !== undefined) ask('setDebug', { value: !!settings.debug }).catch(function () {});
        pushPageOptions();
        if (settings.autoApply && settings.enabled) scheduleAuto(state.videoId, autoDelay(600), true);
      }
    });
  } catch (e) { /* ignore */ }

  /* ------------------------------------------------------------------ *
   * Communicatie met de page agent
   * ------------------------------------------------------------------ */
  var seq = 0;
  var pending = Object.create(null);

  function ask(type, payload, timeoutMs) {
    return new Promise(function (resolve, reject) {
      var id = ++seq;
      var timer = setTimeout(function () {
        delete pending[id];
        reject(new Error('timeout:' + type));
      }, timeoutMs || 4000);
      pending[id] = { resolve: resolve, reject: reject, timer: timer };
      window.postMessage({ __sc: true, dir: 'to-page', id: id, type: type, payload: payload || null }, location.origin);
    });
  }

  window.addEventListener('message', function (ev) {
    if (ev.source !== window) return;
    var d = ev.data;
    if (!d || d.__sc !== true || d.dir !== 'to-content') return;

    if (d.type === 'reply') {
      var p = pending[d.id];
      if (!p) return;
      delete pending[d.id];
      clearTimeout(p.timer);
      if (d.ok) p.resolve(d.result);
      else p.reject(new Error(d.error || 'page-agent-error'));
      return;
    }
    onPageEvent(d);
  });

  function onPageEvent(d) {
    switch (d.type) {
      case 'videoChanged':
        state.videoId = d.videoId;
        state.retryCount = 0;
        state.waitingPlayback = null;
        setBadge(state.subtitlesOff ? 'off' : '');
        if (settings.autoApply && settings.enabled) scheduleAuto(d.videoId, autoDelay(1800));
        break;

      case 'subtitlesOffChanged':
        applySubtitlesOff(!!d.off, 'button');
        if (!d.off) {
          var vidOn = d.videoId || state.videoId;
          delete state.optedOut[vidOn];
          delete state.fixed[vidOn];
          if (settings.autoApply && settings.enabled) scheduleAuto(vidOn, autoDelay(600), true);
        }
        break;

      case 'adChanged':
        if (!d.adShowing && settings.autoApply && settings.enabled && d.videoId) scheduleAuto(d.videoId, autoDelay(1200));
        break;

      case 'playerState':
        if (d.state === 1 && state.waitingPlayback && state.waitingPlayback.videoId === d.videoId) {
          state.waitingPlayback = null;
          scheduleAuto(d.videoId, autoDelay(1500), true);
        }
        break;

      case 'captionChanged':
        // YouTube zet de vertaling (soms) opnieuw aan -> nog een keer corrigeren.
        if (d.translated && d.captionsOn && settings.autoApply && settings.enabled && settings.fixTranslation) {
          var vid = d.videoId;
          var now = Date.now();
          var last = state.fixCooldown[vid] || 0;
          if (now - last > 20000) {
            state.fixCooldown[vid] = now;
            scheduleAuto(vid, autoDelay(900), true);
          }
        }
        break;

      default:
        break;
    }
  }

  /* ------------------------------------------------------------------ *
   * Toast in de player
   * ------------------------------------------------------------------ */
  function ensureToastStyle() {
    if (document.getElementById('sc-toast-style')) return;
    var s = document.createElement('style');
    s.id = 'sc-toast-style';
    s.textContent =
      '#sc-toast{position:absolute;left:14px;bottom:74px;z-index:2147483000;padding:8px 12px;border-radius:8px;' +
      'font:600 13px/1.35 "YouTube Sans","Roboto",Arial,sans-serif;color:#eaf6ff;background:rgba(12,16,24,.92);' +
      'border:1px solid rgba(0,229,255,.55);box-shadow:0 4px 16px rgba(0,0,0,.5);max-width:min(520px,60%);' +
      'pointer-events:none;opacity:0;transform:translateY(6px);transition:opacity .18s ease,transform .18s ease}' +
      '#sc-toast.sc-show{opacity:1;transform:translateY(0)}' +
      '#sc-toast.sc-err{border-color:rgba(255,86,86,.75)}' +
      '#sc-toast.sc-warn{border-color:rgba(255,208,0,.75)}';
    (document.head || document.documentElement).appendChild(s);
  }

  function toast(text, kind) {
    if (!settings.showToast || !text) return;
    ensureToastStyle();
    var host = document.getElementById('movie_player') || document.body;
    var el = document.getElementById('sc-toast');
    if (!el || !host.contains(el)) {
      if (el && el.parentNode) el.parentNode.removeChild(el);
      el = document.createElement('div');
      el.id = 'sc-toast';
      host.appendChild(el);
    }
    el.textContent = text;
    el.className = 'sc-toast sc-' + (kind || 'ok') + ' sc-show';
    clearTimeout(el._scTimer);
    el._scTimer = setTimeout(function () {
      el.className = 'sc-toast sc-' + (kind || 'ok');
    }, settings.toastMs || 3800);
  }

  /* ------------------------------------------------------------------ *
   * Badge op het extensie-icoon
   * ------------------------------------------------------------------ */
  function setBadge(text) {
    try {
      chrome.runtime.sendMessage({ type: 'setBadge', text: text || '' }, function () { void chrome.runtime.lastError; });
    } catch (e) { /* ignore */ }
  }

  /* ------------------------------------------------------------------ *
   * Kill switch per tabblad (het CC-knopje in de speler)
   *
   * Staat hij uit, dan doet dit tabblad helemaal niets meer: geen captions,
   * geen Caption Boost, geen bridge/audio-analyse. De status wordt in de
   * service worker per tab bewaard, zodat een herlaadbeurt hem niet wist.
   * ------------------------------------------------------------------ */
  /**
   * Getal uit de instellingen met een terugvalwaarde. Let op: 0 is een geldige
   * waarde (bv. Y-offset 0), dus niet met `||` werken maar met `isFinite`.
   */
  function numOr(value, fallback) {
    if (value === '' || value === null || value === undefined) return fallback;
    var n = Number(value);
    return isFinite(n) ? n : fallback;
  }

  function pushPageOptions() {
    ask('setOptions', {
      captionBoost: !!settings.captionBoost,
      captionSize: numOr(settings.captionSize, 175),
      captionLines: Number(settings.captionLines) === 1 ? 1 : 2,
      captionOffset: numOr(settings.captionOffset, 7),
      captionWidth: numOr(settings.captionWidth, 70),
      captionFont: settings.captionFont || 'youtube',
      captionWeight: numOr(settings.captionWeight, 500),
      captionWordByWord: !!settings.captionWordByWord
    }).catch(function () {});
  }

  function setTabDisabledBg(off) {
    try {
      chrome.runtime.sendMessage({ type: 'setTabDisabled', off: !!off }, function () { void chrome.runtime.lastError; });
    } catch (e) { /* ignore */ }
  }

  function getTabDisabled() {
    return new Promise(function (resolve) {
      try {
        chrome.runtime.sendMessage({ type: 'getTabState' }, function (res) {
          void chrome.runtime.lastError;
          resolve(!!(res && res.subtitlesOff));
        });
      } catch (e) {
        resolve(false);
      }
    });
  }

  function applySubtitlesOff(off, source) {
    state.subtitlesOff = !!off;
    setTabDisabledBg(state.subtitlesOff);
    setBadge(state.subtitlesOff ? 'off' : '');
    if (state.subtitlesOff) {
      clearTimeout(state.autoTimer);
      clearTimeout(state.retry);
      state.waitingPlayback = null;
    }
    // Het CC-knopje meldt beide richtingen; de hotkey alleen "uit" (bij "aan"
    // vertelt run() zelf wat er gebeurd is).
    if (!settings.showToast) return;
    if (source === 'button' || (source === 'hotkey' && state.subtitlesOff)) {
      toast(state.subtitlesOff ? 'Ondertitels uit voor dit tabblad' : 'Ondertitels weer aan voor dit tabblad',
        state.subtitlesOff ? 'warn' : 'ok');
    }
  }

  /** Zet de kill switch van dit tabblad aan of uit (eigen status + page agent). */
  function setSubtitlesOff(off, source) {
    applySubtitlesOff(!!off, source);
    return ask('setSubtitlesOff', { off: !!off }).catch(function () {});
  }

  function clearSubtitlesOff(source) {
    if (!state.subtitlesOff) return Promise.resolve();
    return setSubtitlesOff(false, source);
  }

  /* ------------------------------------------------------------------ *
   * Hotkey
   *
   * Standaard: geforceerd corrigeren ("Nu toepassen" met de hand).
   * Met de optie `hotkeyToggleSubtitles` wordt de hotkey een echte
   * aan/uit-schakelaar voor dít tabblad (dezelfde kill switch als het
   * CC-knopje in de speler); bij "aan" geldt de bestaande logica.
   * Met de optie `hotkeyEnabled` uit (of een leeg hotkey-veld) doet de
   * hotkey niets: geen actie, geen toast en geen preventDefault().
   * ------------------------------------------------------------------ */
  function isTypingTarget(el) {
    if (!el) return false;
    var tag = (el.tagName || '').toUpperCase();
    if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return true;
    if (el.isContentEditable) return true;
    return false;
  }

  function hotkeyMatches(ev) {
    // Een leeg veld betekent "hotkey uit" (niet: terug naar ']').
    var raw = settings.hotkey;
    var hk = String(raw === null || raw === undefined ? ']' : raw).trim().toLowerCase();
    if (!hk) return false;
    var parts = hk.split('+').map(function (s) { return s.trim(); }).filter(Boolean);
    var key = parts.pop();
    var needCtrl = parts.indexOf('ctrl') !== -1 || parts.indexOf('control') !== -1;
    var needAlt = parts.indexOf('alt') !== -1;
    var needShift = parts.indexOf('shift') !== -1;

    if (!!ev.ctrlKey !== needCtrl) return false;
    if (!!ev.altKey !== needAlt) return false;
    if (!!ev.shiftKey !== needShift) return false;
    if (ev.metaKey) return false;

    var pressed = String(ev.key || '').toLowerCase();
    if (pressed === key) return true;
    // ']' heeft op sommige layouts code 'BracketRight'
    if (key === ']' && String(ev.code || '') === 'BracketRight') return true;
    return false;
  }

  window.addEventListener('keydown', function (ev) {
    if (!settings.enabled) return;
    // Hotkey uit (optie of leeg veld): geen actie, geen toast en de toets
    // blijft gewoon naar de pagina gaan (geen preventDefault).
    if (settings.hotkeyEnabled === false || !settings.hotkey) return;
    if (ev.repeat || ev.isComposing) return;
    if (isTypingTarget(ev.target)) return;
    if (!hotkeyMatches(ev)) return;
    ev.preventDefault();
    ev.stopPropagation();

    var action = L.hotkeyAction({
      enabled: settings.enabled,
      hotkeyEnabled: settings.hotkeyEnabled !== false,
      hotkeyToggle: settings.hotkeyToggleSubtitles,
      subtitlesOff: state.subtitlesOff
    });
    if (action === 'none') return;

    // 'toggle-off': dezelfde kill switch als het CC-knopje in de speler -
    // captions uit, geen Caption Boost en niets meer naar de bridge.
    if (action === 'toggle-off') {
      setSubtitlesOff(true, 'hotkey');
      return;
    }

    // 'toggle-on' én 'run': de kill switch van dit tabblad gaat eerst uit -
    // een hotkey is een expliciet verzoek om de ondertitels weer te regelen.
    clearSubtitlesOff('hotkey').then(function () { run('hotkey'); });
  }, true);

  /* ------------------------------------------------------------------ *
   * Gebruiker zet zelf ondertitels uit -> niet steeds opnieuw aanzetten
   * ------------------------------------------------------------------ */
  document.addEventListener('click', function (ev) {
    var btn = ev.target && ev.target.closest ? ev.target.closest('.ytp-subtitles-button') : null;
    if (!btn) return;
    if (!settings.respectUserOff) return;
    var vid = state.videoId;
    if (!vid) return;
    setTimeout(function () {
      var cur = state.lastProbe && state.lastProbe.current;
      var on = document.querySelector('.ytp-subtitles-button');
      var pressed = on ? on.getAttribute('aria-pressed') === 'true' : false;
      if (!pressed) {
        state.optedOut[vid] = true;
        setBadge('off');
      } else {
        delete state.optedOut[vid];
      }
      void cur;
    }, 350);
  }, true);

  /* ------------------------------------------------------------------ *
   * Prestaties: rustig omgaan met de speler (vooral in playlists)
   *
   * De extensie kan YouTube's caption-renderer geen CPU geven; ze kan alleen
   * haar eigen zware werk uitstellen of overslaan zodat het afspelen (en dus
   * het tekenen van de ondertitels) zo min mogelijk concurreert.
   * ------------------------------------------------------------------ */
  function isPlaylistContext() {
    try {
      if (L.queryHasPlaylist(location.search)) return true;
      return !!document.querySelector('ytd-playlist-panel-renderer');
    } catch (e) {
      return false;
    }
  }

  /** Langere wachttijd in playlists: eerst de videostart laten afronden. */
  function autoDelay(base) {
    if (settings.captionPriority && isPlaylistContext()) return base + 2200;
    return base;
  }

  /** Extra wachttijd tussen retries in playlists (speler is dan nog druk). */
  function retryDelay() {
    if (settings.captionPriority && isPlaylistContext()) return 2200;
    return 1400;
  }

  /** Snelle, gecachete check of de bridge online én klaar is. */
  function bridgeReady() {
    return new Promise(function (resolve) {
      try {
        chrome.runtime.sendMessage({ type: 'bridgeHealth' }, function (res) {
          void chrome.runtime.lastError;
          resolve(!!(res && res.ok && res.ready));
        });
      } catch (e) {
        resolve(false);
      }
    });
  }

  /* ------------------------------------------------------------------ *
   * Planning
   * ------------------------------------------------------------------ */
  function fixedSignature(info) {
    return info.lang + '|' + (info.auto ? 'asr' : 'man');
  }

  function scheduleAuto(videoId, delay, force) {
    if (!settings.enabled || !settings.autoApply) return;
    if (state.subtitlesOff) return;
    if (!videoId) return;
    if (state.optedOut[videoId] && !force) return;

    var done = state.fixed[videoId];
    if (done && !force) return;

    clearTimeout(state.autoTimer);
    state.autoTimer = setTimeout(function () { run('auto'); }, delay || 1200);
  }

  /* ------------------------------------------------------------------ *
   * Hoofdflow
   * ------------------------------------------------------------------ */
  async function run(trigger) {
    if (!settings.enabled) return;
    if (state.subtitlesOff) return;
    if (state.busy) return;
    state.busy = true;

    try {
      var probe = await ask('probe', null, 5000);
      if (!probe || !probe.ok) return;

      state.lastProbe = probe;
      var videoId = probe.videoId;
      if (!videoId) return;
      state.videoId = videoId;

      if (trigger === 'hotkey') {
        delete state.optedOut[videoId];
        delete state.fixed[videoId];
      }
      if (state.optedOut[videoId] && trigger !== 'hotkey') return;

      if (probe.adShowing) {
        if (trigger === 'hotkey' && settings.showToast) toast('Even wachten - er speelt een advertentie', 'warn');
        else scheduleAuto(videoId, 2500);
        return;
      }

      // Nog niet klaar met laden? (geen tracks bekend, speler nog niet begonnen)
      var notReady = !probe.tracks.length && !probe.current;
      if (notReady && state.retryCount < 6) {
        state.retryCount++;
        clearTimeout(state.retry);
        state.retry = setTimeout(function () { run(trigger); }, retryDelay());
        return;
      }

      var det = L.detectAudioLanguage(probe);
      var viaBridge = false;

      var fallback = L.shouldUseAudioFallback({
        enabled: settings.audioFallback,
        trigger: trigger,
        inPlaylist: isPlaylistContext(),
        captionPriority: settings.captionPriority,
        allowInPlaylists: settings.audioFallbackInPlaylists,
        lastCaptureAt: state.lastCaptureAt,
        now: Date.now(),
        cooldownMs: CAPTURE_COOLDOWN_MS
      });
      if (!fallback.allowed && (!det.lang || det.ambiguous) && settings.debug) {
        console.log('[SC] audio-analyse overgeslagen:', fallback.reason);
      }

      if ((!det.lang || det.ambiguous) && fallback.allowed) {
        if (probe.playerState === 1) {
          // Niet opnemen als de bridge niet klaar is: dat kost alleen CPU/GPU.
          var ready = await bridgeReady();
          var br = null;
          if (ready) {
            state.lastCaptureAt = Date.now();
            br = await bridgeDetect();
          }
          if (br && br.ok && br.language) {
            viaBridge = true;
            det = {
              lang: L.isSupported(br.language) ? L.baseLang(br.language) : null,
              source: 'audio-analysis',
              ambiguous: false,
              outOfScope: br.language && !L.isSupported(br.language) ? br.language : null,
              candidates: []
            };
          } else if (trigger === 'hotkey' && settings.showToast) {
            toast('Audio-analyse niet gelukt (' + ((br && br.reason) || (ready ? 'onbekend' : 'bridge niet klaar')) + ')', 'warn');
          }
        } else {
          // Nog geen audio: probeer opnieuw zodra het filmpje speelt.
          state.waitingPlayback = { videoId: videoId, at: Date.now() };
          if (trigger === 'hotkey' && settings.showToast) toast('Start de video even - daarna kan ik de audiotaal horen', 'warn');
          return;
        }
      }

      var plan = L.planFix(probe, {
        detected: det.lang,
        detectedSource: viaBridge ? 'audio-analysis' : det.source,
        preferAutoGenerated: settings.preferAutoGenerated,
        forceSubtitlesOn: settings.forceSubtitlesOn
      });

      state.lastResult = { plan: plan, at: Date.now() };

      if (plan.action === 'none') {
        state.fixed[videoId] = { sig: fixedSignature(plan), at: Date.now(), lang: plan.lang };
        if (trigger === 'hotkey' && settings.showToast) toast(L.toastText(plan, null), 'ok');
        setBadge(L.shortLabel(plan.lang) + (plan.target && plan.target.isAutoGenerated ? '' : '*'));
        return;
      }

      if (plan.action === 'unknown') {
        if (trigger === 'hotkey' && settings.showToast) toast(L.toastText(plan, null), 'warn');
        if (plan.ambiguous) setBadge('?');
        return;
      }

      if (plan.action === 'no-track') {
        if (settings.showToast) toast(L.toastText(plan, null), 'warn');
        state.fixed[videoId] = { sig: 'none', at: Date.now(), lang: plan.lang };
        setBadge('!');
        return;
      }

      var res = await ask('apply', { target: plan.target, allowManualFallback: settings.preferAutoGenerated }, 20000);
      if (res && res.ok) {
        var usedAuto = !!(res.target ? res.target.isAutoGenerated : plan.target.isAutoGenerated);
        state.fixed[videoId] = { sig: plan.lang + '|' + (usedAuto ? 'asr' : 'man'), at: Date.now(), lang: plan.lang };
        setBadge(L.shortLabel(plan.lang) + (usedAuto ? '' : '*'));
      }
      if (settings.showToast) toast(L.toastText(plan, res), res && res.ok ? 'ok' : 'err');
      if (settings.debug) console.log('[SC] apply resultaat', plan, res, probe);

    } catch (e) {
      if (settings.debug) console.warn('[SC] run() fout', e);
      if (trigger === 'hotkey' && settings.showToast) toast('Subtitle Corrector: ' + (e.message || e), 'err');
    } finally {
      state.busy = false;
    }
  }

  /* ------------------------------------------------------------------ *
   * Lokale bridge (audio-analyse)
   * ------------------------------------------------------------------ */
  function bridgeDetect() {
    return new Promise(function (resolve) {
      var done = false;
      var timer = setTimeout(function () { if (!done) { done = true; resolve({ ok: false, reason: 'timeout' }); } }, 30000);
      try {
        chrome.runtime.sendMessage({
          type: 'detectAudio',
          seconds: settings.audioSeconds,
          keepAudio: settings.keepAudioDuringCapture,
          minConfidence: settings.minConfidence
        }, function (res) {
          void chrome.runtime.lastError;
          if (done) return;
          done = true;
          clearTimeout(timer);
          resolve(res || { ok: false, reason: 'no-response' });
        });
      } catch (e) {
        clearTimeout(timer);
        resolve({ ok: false, reason: 'extension-error' });
      }
    });
  }

  /* ------------------------------------------------------------------ *
   * Berichten vanaf de popup
   * ------------------------------------------------------------------ */
  try {
    chrome.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
      if (!msg || typeof msg !== 'object') return;
      if (msg.type === 'popupRun') {
        clearSubtitlesOff('popup').then(function () {
          delete state.fixed[state.videoId];
          delete state.optedOut[state.videoId];
          run('hotkey');
        });
        sendResponse({ ok: true });
        return true;
      }
      if (msg.type === 'popupState') {
        sendResponse({
          ok: true,
          videoId: state.videoId,
          probe: state.lastProbe,
          result: state.lastResult,
          settings: settings
        });
        return true;
      }
      return false;
    });
  } catch (e) { /* ignore */ }

  /* ------------------------------------------------------------------ *
   * Start
   * ------------------------------------------------------------------ */
  loadSettings(function () {
    if (settings.debug) ask('setDebug', { value: true }).catch(function () {});
    pushPageOptions();
    // kill switch van dit tabblad herstellen (bv. na een herlaadbeurt)
    getTabDisabled().then(function (off) {
      state.subtitlesOff = off;
      if (off) setBadge('off');
      ask('setSubtitlesOff', { off: off }).catch(function () {});
    });
    // eerste probe, zodat de popup direct iets kan tonen
    ask('probe', null, 5000).then(function (p) {
      if (p && p.ok) {
        state.lastProbe = p;
        state.videoId = p.videoId;
      }
    }).catch(function () {});
  });
})();
