/*
 * SubtitleCorrector - instellingenpagina.
 * Leest/schrijft chrome.storage.sync. Zelfde defaults als content.js.
 */
'use strict';

const DEFAULTS = {
  enabled: true,
  hotkey: ']',
  hotkeyEnabled: false,
  autoApply: true,
  preferAutoGenerated: true,
  forceSubtitlesOn: true,
  respectUserOff: true,
  fixTranslation: true,
  audioFallback: true,
  captionPriority: true,
  audioFallbackInPlaylists: false,
  captionBoost: true,
  captionSize: 130,
  captionLines: 2,
  captionOffset: 9,
  captionOffsetX: -9,
  captionWidth: 50,
  captionFont: 'youtube',
  captionWeight: 400,
  captionWordByWord: true,
  bridgeUrl: 'http://127.0.0.1:8791',
  audioSeconds: 5,
  minConfidence: 0.5,
  keepAudioDuringCapture: true,
  showToast: true,
  toastMs: 3800,
  debug: false
};

const BOOL_FIELDS = [
  'enabled', 'hotkeyEnabled', 'autoApply', 'preferAutoGenerated', 'forceSubtitlesOn', 'respectUserOff',
  'fixTranslation', 'audioFallback', 'captionPriority', 'audioFallbackInPlaylists', 'captionBoost',
  'captionWordByWord', 'keepAudioDuringCapture', 'showToast', 'debug'
];
const TEXT_FIELDS = ['hotkey', 'bridgeUrl', 'captionFont'];
const NUM_FIELDS = ['audioSeconds', 'minConfidence', 'captionSize', 'captionLines', 'captionOffset', 'captionOffsetX', 'captionWidth', 'captionWeight'];

// Gedeelde logica (lang-utils.js) voor de lettertypestacks en de clamping.
const L = window.SCLang || null;

const $ = (id) => document.getElementById(id);

function status(text, isError) {
  const el = $('status');
  el.textContent = text;
  el.className = isError ? 'err' : '';
  if (text) setTimeout(() => { if (el.textContent === text) el.textContent = ''; }, 3500);
}

function fill(settings) {
  BOOL_FIELDS.forEach((k) => { $(k).checked = !!settings[k]; });
  TEXT_FIELDS.forEach((k) => { $(k).value = settings[k] || ''; });
  NUM_FIELDS.forEach((k) => { $(k).value = settings[k]; });
}

/*
 * Een leeg hotkey-veld betekent "hotkey uit". Laat dat expliciet zien in
 * plaats van een placeholder die op een echte waarde lijkt.
 */
function syncHotkeyPlaceholder() {
  const el = $('hotkey');
  if (!el) return;
  el.placeholder = String(el.value || '').trim() ? ']' : '<empty>';
}

function collect() {
  const out = {};
  BOOL_FIELDS.forEach((k) => { out[k] = !!$(k).checked; });
  TEXT_FIELDS.forEach((k) => { out[k] = String($(k).value || '').trim(); });
  NUM_FIELDS.forEach((k) => { out[k] = Number($(k).value); });

  // Het hotkey-veld mag leeg blijven: dat betekent "hotkey uit".
  if (!out.bridgeUrl) out.bridgeUrl = DEFAULTS.bridgeUrl;
  out.audioSeconds = Math.max(2, Math.min(10, Math.round(out.audioSeconds || 5)));
  out.minConfidence = Math.max(0, Math.min(1, isFinite(out.minConfidence) ? out.minConfidence : 0.5));
  out.captionSize = Math.max(50, Math.min(250, Math.round(out.captionSize || 130)));
  out.captionLines = Number(out.captionLines) === 1 ? 1 : 2;
  out.captionOffset = Math.max(-40, Math.min(30, Math.round(isFinite(out.captionOffset) ? out.captionOffset : 9)));
  out.captionOffsetX = Math.max(-40, Math.min(40, Math.round(isFinite(out.captionOffsetX) ? out.captionOffsetX : -9)));
  if (L) {
    out.captionWidth = L.captionBarWidthPct(out.captionWidth);
    out.captionFont = L.captionFontKey(out.captionFont);
    out.captionWeight = L.captionFontWeight(out.captionWeight);
  }
  return out;
}

/*
 * De lettertypelijst komt uit de gedeelde logica (lang-utils.js), zodat de
 * sleutels en de CSS-stacks op één plek staan. Zonder dat script blijft de
 * fallback uit de HTML staan (alleen YouTube's eigen font).
 */
function fillFontOptions() {
  const sel = $('captionFont');
  const fonts = (L && L.CAPTION_FONTS) || [];
  if (!sel || fonts.length < 2) return;
  sel.textContent = '';
  fonts.forEach((f) => {
    const o = document.createElement('option');
    o.value = f.key;
    o.textContent = f.label;
    sel.appendChild(o);
  });
}
fillFontOptions();

/*
 * De letterdiktelijst komt uit dezelfde bron (lang-utils.js): 300 t/m 700 in
 * stappen van 25. Zonder dat script blijft de fallback uit de HTML staan
 * (alleen 400). De standaard krijgt een label, de rest is het getal zelf.
 */
function fillWeightOptions() {
  const sel = $('captionWeight');
  const weights = (L && L.CAPTION_WEIGHTS) || [];
  if (!sel || weights.length < 2) return;
  sel.textContent = '';
  weights.forEach((w) => {
    const o = document.createElement('option');
    o.value = String(w);
    o.textContent = String(w) + (w === L.CAPTION_WEIGHT_DEFAULT ? ' (normaal, standaard)' : '');
    sel.appendChild(o);
  });
  // Zonder opgeslagen waarde (of als fill() niet langskomt) moet de standaard
  // geselecteerd staan en niet de eerste optie van de lijst (300).
  sel.value = String(L.CAPTION_WEIGHT_DEFAULT);
}
fillWeightOptions();

chrome.storage.sync.get(DEFAULTS, (items) => { fill(items); syncHotkeyPlaceholder(); });

$('hotkey').addEventListener('input', syncHotkeyPlaceholder);

$('save').addEventListener('click', () => {
  const values = collect();
  chrome.storage.sync.set(values, () => {
    fill(values);
    syncHotkeyPlaceholder();
    status('Opgeslagen');
  });
});

$('reset').addEventListener('click', () => {
  chrome.storage.sync.set(DEFAULTS, () => {
    fill(DEFAULTS);
    syncHotkeyPlaceholder();
    status('Standaardwaarden hersteld');
  });
});

$('test').addEventListener('click', () => {
  const url = String($('bridgeUrl').value || DEFAULTS.bridgeUrl).replace(/\/+$/, '');
  status('Bezig...');
  fetch(url + '/health', { cache: 'no-store' })
    .then((r) => r.json())
    .then((j) => {
      const model = j.model ? ' model=' + j.model : '';
      const backend = j.backend ? ' backend=' + j.backend : '';
      if (j.ok && j.ready) status('Bridge online.' + backend + model);
      else if (j.ok) status('Bridge online, model wordt nog geladen...' + backend + model);
      else status('Bridge antwoordt, maar niet klaar: ' + (j.error || 'onbekend'), true);
    })
    .catch((e) => status('Geen verbinding met de bridge (' + (e.message || e) + ')', true));
});
