/*
 * SubtitleCorrector - popup.
 * Toont de status van de actieve YouTube-tab en kan de correctie handmatig starten.
 */
'use strict';

const L = globalThis.SCLang;
const $ = (id) => document.getElementById(id);

function setText(id, text, cls) {
  const el = $(id);
  el.textContent = text;
  el.className = 'v' + (cls ? ' ' + cls : '');
}

function activeTab() {
  return new Promise((resolve) => {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => resolve(tabs && tabs[0] ? tabs[0] : null));
  });
}

function sendToTab(tabId, msg) {
  return new Promise((resolve) => {
    try {
      chrome.tabs.sendMessage(tabId, msg, (res) => {
        void chrome.runtime.lastError;
        resolve(res || null);
      });
    } catch (e) {
      resolve(null);
    }
  });
}

function sendBg(msg) {
  return new Promise((resolve) => {
    try {
      chrome.runtime.sendMessage(msg, (res) => {
        void chrome.runtime.lastError;
        resolve(res || null);
      });
    } catch (e) {
      resolve(null);
    }
  });
}

function labelTrack(cur) {
  if (!cur) return 'uit';
  const kind = cur.isAutoGenerated ? 'auto' : 'handmatig';
  let s = L.shortLabel(cur.languageCode) + ' (' + kind + ')';
  if (cur.translated) s += ' -> vertaald naar ' + L.shortLabel(cur.translatedTo);
  return s;
}

function labelAudio(probe) {
  if (!probe) return 'onbekend';
  const det = L.detectAudioLanguage(probe);
  const parts = [];
  if (det.lang) {
    const src = {
      'audio-track': 'audiotrack',
      'current-asr': 'ASR-track',
      'asr-track': 'ASR-track',
      'default-audio-language': 'video-metadata'
    }[det.source] || det.source;
    parts.push(L.shortLabel(det.lang) + ' (' + src + ')');
  } else {
    parts.push('onbekend');
  }
  if (probe.audioTrack && probe.audioTrack.isAutoDubbed) parts.push('dub');
  if (det.ambiguous) parts.push('tegenstrijdig');
  return parts.join(' ');
}

async function render() {
  const tab = await activeTab();
  const settings = await new Promise((r) => chrome.storage.sync.get({ enabled: true, hotkey: ']', preferAutoGenerated: true, forceSubtitlesOn: true, audioFallback: true, captionWordByWord: false }, r));

  $('hotkey').textContent = settings.hotkey || ']';
  $('wordByWord').checked = !!settings.captionWordByWord;
  setText('enabled', settings.enabled ? 'aan' : 'uit', settings.enabled ? 'ok' : 'err');

  const health = await sendBg({ type: 'bridgeHealth' });
  if (!health || !health.ok) {
    setText('bridge', 'offline', 'err');
    setText('model', health && health.url ? health.url : '-', 'muted');
  } else if (!health.ready) {
    setText('bridge', 'online (model laden...)', 'warn');
    setText('model', (health.backend || '?') + ' / ' + (health.model || '?'), 'muted');
  } else {
    setText('bridge', 'online', 'ok');
    setText('model', (health.backend || '?') + ' / ' + (health.model || '?'), 'muted');
  }

  if (!tab || !/^https:\/\/(www|m)\.youtube\.com\//.test(tab.url || '')) {
    setText('video', 'geen YouTube-tab');
    setText('audio', '-');
    setText('caption', '-');
    setText('action', '-');
    $('apply').disabled = true;
    return;
  }

  const st = await sendToTab(tab.id, { type: 'popupState' });
  if (!st || !st.probe) {
    setText('video', 'extensie nog niet actief - ververs de pagina');
    setText('audio', '-');
    setText('caption', '-');
    setText('action', '-');
    $('apply').disabled = true;
    return;
  }

  const probe = st.probe;
  $('apply').disabled = false;
  setText('video', probe.title ? (probe.title.length > 46 ? probe.title.slice(0, 46) + '...' : probe.title) : (probe.videoId || '-'));
  setText('audio', labelAudio(probe));
  setText('caption', labelTrack(probe.current), probe.current && probe.current.translated ? 'warn' : '');

  const det = L.detectAudioLanguage(probe);
  const plan = L.planFix(probe, {
    detected: det.lang,
    detectedSource: det.source,
    preferAutoGenerated: settings.preferAutoGenerated,
    forceSubtitlesOn: settings.forceSubtitlesOn
  });
  const actionText = plan.action === 'apply'
    ? 'zet ' + L.shortLabel(plan.lang) + ' ' + (plan.target.isAutoGenerated ? 'auto' : 'handmatig') + ' (' + L.describePlan(plan) + ')'
    : L.describePlan(plan);
  setText('action', actionText, plan.action === 'apply' ? 'warn' : (plan.action === 'none' ? 'ok' : 'err'));
}

$('apply').addEventListener('click', async () => {
  const tab = await activeTab();
  if (!tab) return;
  $('apply').textContent = 'Bezig...';
  await sendToTab(tab.id, { type: 'popupRun' });
  setTimeout(() => { $('apply').textContent = 'Nu toepassen'; render(); }, 2500);
});

$('options').addEventListener('click', () => chrome.runtime.openOptionsPage());

// Word-for-Word meteen bewaren: de content script duwt de nieuwe optie direct
// naar de page agent (chrome.storage.onChanged), dus het werkt meteen door.
$('wordByWord').addEventListener('change', () => {
  chrome.storage.sync.set({ captionWordByWord: $('wordByWord').checked });
});

$('recheck').addEventListener('click', async () => {
  $('recheck').textContent = 'Checken...';
  await sendBg({ type: 'bridgeHealth', force: true });
  $('recheck').textContent = 'Bridge checken';
  render();
});

render();
